# Docker Compose version v2.29.7
services:
  yolo11-xview:
    image: yolo11-xview
    build: .
    volumes:
      - ./datasets:/datasets:ro
      - latest:/app/latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
volumes:
  latest:
