# Docker Compose version v2.29.7
services:
  yolo11-xview:
    image: yolo11-xview
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
